name: hire_harmony
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  badges: ^3.1.2
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  camera: ^0.11.0+2
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.4
  crypto: ^3.0.6
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.2.0
  dot_navigation_bar: ^1.0.2
  drop_down_list: ^2.0.0
  dropdown_search: ^6.0.2
  encrypt: ^5.0.3
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.8.1
  firebase_messaging: ^15.2.1
  fluid_bottom_nav_bar: ^1.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_face_api: ^6.4.875
  flutter_face_core_basic: ^6.4.242
  flutter_local_notifications: ^18.0.1
  flutter_slidable: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.8
  geolocator: ^13.0.2
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  gradient_icon: ^2.0.9
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  location: ^8.0.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  persistent_bottom_nav_bar_v2: ^5.3.1
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/customer.png
    - lib/assets/images/employee.png
    - lib/assets/images/adminmalak.jpeg
    - lib/assets/images/handicraft.png
    - lib/assets/images/tool-box.png
    - lib/assets/images/education.png
    - lib/assets/images/mechanic.png
    - lib/assets/images/chef.png
    - lib/assets/images/growth.png
    - lib/assets/images/office.jpg
    - lib/assets/images/teacher.jpg
    - lib/assets/images/shose.jpg
    - lib/assets/images/office2.jpg
    - lib/assets/images/ServManage.jpeg
    - lib/assets/images/ServManage.jpeg
    - lib/assets/images/ServManage.jpeg
    - lib/assets/images/catgManage.webp
    - lib/assets/images/accControl.jpeg
    - lib/assets/images/adManage.jpeg
    - lib/assets/images/adManage.jpg
    - lib/assets/images/notf.jpg
    - lib/assets/images/welcome.jpg
    - lib/assets/images/welcome3.jpg
    - lib/assets/categories.csv
